server:
  main:
    banner-mode: off
  port: 7003
  error:
    include-message: always
spring:
  profiles:
    active: @activatedProfile@
  jpa:
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off

logging:
  level:
    root: info
    com.salapp.product: debug

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:~/testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: sonar
  datasource:
    url: jdbc:h2:mem:~/testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
server:
  port: 8080
