
server:
  port: 7001
  error:
    include-message: always

  profiles:
    active: @activatedProfile@
  main:
    banner-mode: off
logging:
  level:
    root: info
    com.salapp.product: debug
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080
