server:
  port: 7002
  error:
    include-message: always
spring:
  profiles:
    active: @activatedProfile@
  main:
    banner-mode: off
logging:
  level:
    root: info
    com.salapp.product: debug

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
---
spring:
  config:
    activate:
      on-profile: sonar
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
